spring:
  application:
    name: 49-Config-Server-Client-App   # 👈 The name used to fetch the correct YAML file from Config Server
  config:
    import: optional:configserver:http://localhost:9090  # 👈 URL of your Config Server
server:
  port: 9091  # 👈 Local port where this client (microservice) will run
