spring:
  application:
    name: 45-SBMS-API-GATEWAY

  main:
    web-application-type: servlet

  cloud:
    gateway:
      mvc:  # ✅ not under server
        routes:
          - id: greet-api
            uri: lb://43-GREET-API
            predicates:
              - Path=/greet/**
          - id: welcome-api
            uri: lb://44-WELCOMEAPI-INTERSERVICECOMMUNICATION-MONITOR
            predicates:
              - Path=/welcome/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 2222

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway.server.mvc: TRACE
