spring:
  application:
    name: 17-DataJpa-CompositePK-App
  datasource:
    url: jdbc:mysql://localhost:3306/sbms
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
