spring:
  application:
    name: 43-GREET-API
  boot:
    admin:
      client:
        url: http://localhost:1111/
management:
  endpoints:
    web:
      exposure:
        include: '*'
#commenting port for load balancing
#server:
#  port: 9090
