spring:
  application:
    name: 44-WelcomeAPI-InterServiceCommunication-Monitor
  boot:
    admin:
      client:
        url: http://localhost:1111/
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9090
