spring:
  application:
    name: 16-CustomGenerator-App
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.OracleDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true